### ISSUE TITLE
Could not find a declaration file for module 'react-screen-wake-lock'.

### ISSUE THREAD

**Issue by Vikeo** [jorisre/react-screen-wake-lock#262]
I want to use this package for my React (TypeScript+SWC) app that I created using the `npm create vite@latest` script. 

When I try to import `useWakeLock` I get this error.

> Could not find a declaration file for module 'react-screen-wake-lock'. 
> '../node_modules/react-screen-wake-lock/dist/react-screen-wake-lock.esm.js' implicitly has an 'any' type.

>   There are types at '../node_modules/react-screen-wake-lock/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-screen-wake-lock' library may need to update its package.json or typings.ts(7016)
> 

While it still works if i set `"strict": false,` in my tsconfig.json, but I don't want to do that. 
Is this something that warrants a fix?

**Comment by jorisre** [comment]
Thanks for reporting the issue, can you try the latest version `3.0.2`?

**Comment by Vikeo** [comment]
It works, thanks!
